### ISSUE TITLE
why had this not been reported? 1.19.3 Failure to correctly load

### ISSUE THREAD

**Issue by Zelioth** [Wouink/furnish#20]
1.19.3 Minecraft
Forge 44.1.2
Furnish 17-1.19

Having Furnish in my mod pack that I am creating for the update of Friends United causes this error

[07Jan2023 16:51:39.011] [modloading-worker-0/INFO] [Furnish/]: Registered Furnish Sounds.
[07Jan2023 16:51:39.030] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: furnish, class io.github.wouink.furnish.Furnish
java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'
	at io.github.wouink.furnish.setup.FurnishItems$1.<init>(FurnishItems.java:22) ~[furnish-17-1.19.jar%23477!/:17-1.19]
	at io.github.wouink.furnish.setup.FurnishItems.<clinit>(FurnishItems.java:22) ~[furnish-17-1.19.jar%23477!/:17-1.19]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.3-44.1.2.jar%23606!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.3-44.1.2.jar%23606!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.3-44.1.2.jar%23606!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.2.jar%23605!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

Removing it fixes this issue and the pack will launch fine.

Will post logs and debug
[latest.log](https://github.com/Wouink/furnish/files/10367333/latest.log)
[debug.log](https://github.com/Wouink/furnish/files/10367334/debug.log)

**Comment by Plisko1** [comment]
Same issue here.  I installed it on my 1.19.3 server running Forge 44.0.1 and it crashed the server pretty hard.  I couldn't get it to stop.  The clients of the players also failed to load the mod.  We uninstalled it and everything is back to normal. 

This is what the console told me as I was restarting with the mod in the server mod folder for the first time:

[Furnish console log.txt](https://github.com/Wouink/furnish/files/10374581/Furnish.console.log.txt)
